name = "statusio"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
# account_id = "" # `wrangler.toml`: disabled & ""

workers_dev = true

kv_namespaces = [ { binding = "STATUSIO_CACHE" } ]
# Automatic Provisioning: developers.cloudflare.com/workers/wrangler/configuration/

[vars]
ACCESS_SECRET = "update-default-access-key"

# [[routes]] # `wrangler.toml`: disabled & "statusio.example.com"
# pattern = "statusio.example.com"
# custom_domain = true

